# Do NOT trigger this pipeline on code push or PR
trigger: none
pr: none

# Trigger this release automatically when the build pipeline finishes
resources:
  pipelines:
  - pipeline: buildPipeline        # alias (you can name anything)
    source: build  # EXACT name of your build pipeline
    trigger: true

stages:
- stage: TestDeploy
  displayName: "Deploy to Test"
  jobs:
  - deployment: DeployToVM
    displayName: "Deploy to Test IIS Server"
    pool:
      name: 'Default'              # Your VM agent pool
    environment: 'Test'            # Your Environment name
    strategy:
      runOnce:
        deploy:
          steps:

          # Download artifact from the triggering build pipeline
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'specific'
              project: $(System.TeamProject)
              pipeline: $(resources.pipeline.buildPipeline.runID)
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'

          # Unzip to IIS folder
          - task: ExtractFiles@1
            inputs:
              archiveFilePatterns: '$(System.ArtifactsDirectory)/drop/drop.zip'
              destinationFolder: 'C:\inetpub\wwwroot\c_sharp'
              cleanDestinationFolder: true

          # Restart IIS
          - powershell: |
              iisreset
            displayName: "Restart IIS"
