# Trigger this release whenever the build pipeline completes
resources:
  pipelines:
  - pipeline: buildPipeline        # alias you choose
    source: azure-build-pipelines  # EXACT name of your build pipeline
    trigger: true

stages:
- stage: TestDeploy
  displayName: "Deploy to Test"
  jobs:
  - deployment: DeployToVM
    displayName: "Deploy to Test IIS Server"
    pool:
      name: 'Default'
    environment: 'Test'
    strategy:
      runOnce:
        deploy:
          steps:

          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'specific'
              project: $(System.TeamProject)
              pipeline: $(resources.pipeline.buildPipeline.runID)
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: ExtractFiles@1
            inputs:
              archiveFilePatterns: '$(System.ArtifactsDirectory)/drop/drop.zip'
              destinationFolder: 'C:\inetpub\wwwroot\c_sharp'
              cleanDestinationFolder: true

          - powershell: |
              iisreset
            displayName: "Restart IIS"
