trigger:
  branches:
    include:
      - main

pool:
    vmImage : 'windows-latest'
    
variables:
    solution: '**/*.sln'
    Buildplatform: 'Any CPU'
    buildConfiguration: 'Release'

steps:
    - checkout: self
      clean: true

    - task: DotNetCoreCLI@2
      displayName: 'Restore Packages'
      inputs: 
        command: 'restore'
        projects: '$(solution)' 
  
     
    - task: DotNetCoreCLI@2
      displayName: 'Build Solution'
      inputs:
        command: 'build'
        projects: '$(solution)'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'publish artifacts'
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        
    - task: ArchiveFiles@2
      displayName: 'Create ZIP package'
      inputs:
          rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/drop.zip'
          replaceExistingArchive: true






       
