trigger: none
pr: none

resources:
  pipelines:
  - pipeline: buildPipeline
    source: build
    trigger: true

stages:
- stage: TestDeploy
  displayName: "Deploy to Test"
  jobs:
  - deployment: DeployToVM
    pool:
      name: 'Default'
    environment: 'Test'
    strategy:
      runOnce:
        deploy:
          steps:

          # Extract ONLY s.zip (Azure already downloaded artifact automatically)
          - task: ExtractFiles@1
            displayName: "Extract s.zip into IIS"
            inputs:
              archiveFilePatterns: '$(Pipeline.Workspace)/buildPipeline/drop/publish/s.zip'
              destinationFolder: 'C:\inetpub\wwwroot\c_sharp'
              cleanDestinationFolder: true

          - powershell: |
              iisreset
            displayName: "Restart IIS"
